name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker linux
      run: |
        docker build -f Docker/linux-x64/Dockerfile -t fbarresi/softplc:1.2.${{ github.run_number }}-linux .
        docker tag fbarresi/softplc:1.2.${{ github.run_number }}-linux fbarresi/softplc:latest-linux
        docker push fbarresi/softplc:1.2.${{ github.run_number }}-linux 
        docker push fbarresi/softplc:latest-linux
      working-directory: ./SoftPlc
    - name: Build Docker arm
      run: |
        docker build -f Docker/arm/Dockerfile -t fbarresi/softplc:1.2.${{ github.run_number }}-arm .
        docker tag fbarresi/softplc:1.2.${{ github.run_number }}-arm fbarresi/softplc:latest-arm
        docker push fbarresi/softplc:1.2.${{ github.run_number }}-arm
        docker push fbarresi/softplc:latest-arm
      working-directory: ./SoftPlc
    - name: Build Docker windows
      run: |
        docker build -f Docker/windows/Dockerfile -t fbarresi/softplc:1.2.${{ github.run_number }}-win .
        docker tag fbarresi/softplc:1.2.${{ github.run_number }}-win fbarresi/softplc:latest-win
        docker push fbarresi/softplc:1.2.${{ github.run_number }}-win
        docker push fbarresi/softplc:latest-win
      working-directory: ./SoftPlc
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 1.2.${{ github.run_number }}
        release_name: 1.2.${{ github.run_number }}
        draft: false
        prerelease: false
    